export const POST__ADD = 'POST__ADD'
export const POST__UPDATE = 'POST__UPDATE'
export const POST__DELETE = 'POST__DELETE'
export const GET_POST_EDIT = 'GET__POST_EDIT'
export const POST_SEARCH = 'POST_SEARCH'
